### ISSUE TITLE
Cycling through suggestion list multiple times prints the option repetitively

### ISSUE THREAD

**Issue by cyangle** [I3oris/ic#11] opened 2022-10-15 16:48 UTC
Cycling through the suggestion list should not select the option.

![Screen Recording 2022-10-15 at 11 41 51 AM](https://user-images.githubusercontent.com/15083254/195998192-42044705-8891-429d-b242-3b915fd431a4.gif)

**Comment by I3oris** [comment] 2022-10-16 07:15
It caused by the equal in `object=`, it's a regression probably got when I extracted the code in REPLy, thank you!

**Comment by I3oris** [comment] 2022-10-16 08:34
Fixed by [this commit](https://github.com/I3oris/ic/commit/84f8162eb5749a5957a2aa075b5c4c33b9a88da1). I forgot to lock the version of REPLy in `shard.yml`.

**Closed by I3oris** 2022-10-16 08:34 UTC
